services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: social_web_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bazi123
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d social_web_test"]
      interval: 5s
      timeout: 5s
      retries: 20


volumes:
  social_web_pgdata:
